APPLICATION_ID = "115742"

APPLICATION_KEY_1 = "BBB1TZT0ftZmoWsl"

APPLICATION_KEY_2 = "Wfh6RQ0W8Y1iDKvX"
CERT_FILE_LOCAITON = "C:/Program Files/OpenSSL-Win64/bin/cert.pem"

USER_NAME = "shanto12@gmail.com"
PASSWORD = ""
